package BlogSport;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


@Controller    // This means that this class is a Controller
public class MainController {
    @RequestMapping("/")
    public String getHomepage() {
        return "index.html";
    }
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PostsRepository postsRepository;


    /* POST the different components of post : title , content (image: later) */
    @RequestMapping(value = "/posts", method= RequestMethod.POST) // Map ONLY GET Requests
    @ResponseBody
    public String addNewPost(@RequestParam(value = "post") String post, @RequestParam(value = "title") String title) {
        // @ResponseBody means the returned String is the response, not a view password
        // @RequestParam means it is a parameter from the GET or POST request
        Posts n = new Posts();
        n.setTitle(title);
        n.setPost(post);
        postsRepository.save(n);
        return "Saved";
    }

    /* GET the different components of a post. the latter are returned as a json file */
    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Posts> getAllUsers() {
        // This returns a JSON or XML with the users
        return postsRepository.findAll();
    }

    /* DELETE */
    @RequestMapping("/delete")
    @ResponseBody
    public String delete(long id) {
        try {
            Posts user = new Posts(id);
            postsRepository.delete(user);
        } catch (Exception ex) {
            return "Error deleting the user:" + ex.toString();
        }
        return "User succesfully deleted!";
    }

    /* PUT (modify) */
    @RequestMapping("/put")
    @ResponseBody
    public String put(@RequestParam(value = "id") long id, @RequestParam(value = "post") String post, @RequestParam(value = "title") String title) {
        try {
            Posts posts = postsRepository.findOne(id);
            posts.setPost(post);
            posts.setTitle(title);
            postsRepository.save(posts);
        } catch (Exception ex) {
            return "Error updating the user: " + ex.toString();
        }
        return "User succesfully updated!";
    }
}
